
#@copyright : Belal Hani Sabha

CC=arm-none-eabi-

CFLAGS=-gdwarf-2 -mcpu=cortex-m4 -g

INCS=-I .

LIBS=

SRC=$(wildcard *.c)
OBJ=$(SRC:.c=.o)  

AS=$(wildcard *.s)
ASO=$(AS:.s=.o)

PROJECT_NAME=Tiva-C

all: $(PROJECT_NAME).bin
	@echo "build is done"

%.o: %.c
	$(CC)gcc.exe -c $(CFLAGS) $(INCS) $< -o $@

%.txt: %.o 
	$(CC)nm.exe   $< >  $@


$(PROJECT_NAME).elf: $(OBJ) $(ASO)
	$(CC)ld.exe -T linker.ld $(LIBS) $(OBJ) $(ASO) -o $@ -Map=mab_file.map
	cp $(PROJECT_NAME).elf $(PROJECT_NAME).axf

$(PROJECT_NAME).bin: $(PROJECT_NAME).elf
	$(CC)objcopy.exe -O binary $< $@

clean_all:
	rm  *.o *.elf *.bin *.map 
	@echo "everything clean..."

clean:
	rm  *.bin *.elf
	@echo "clean .elf and .bin files"