
#@copyright : Belal Hani Sabha

CC=arm-none-eabi-

CFLAGS=-g -mcpu=arm926ej-s

INCS=-I .

LIBS=

SRC=$(wildcard *.c)
OBJ=$(SRC:.c=.o)  # uart.o app.o

AS=$(wildcard *.s)
ASO=$(AS:.s=.o)

PROJECT_NAME=belal

all: $(PROJECT_NAME).bin
	@echo "build is done"

%.o: %.c
	$(CC)gcc.exe -c $(CFLAGS) $(INCS) $< -o $@

startup.o: startup.s
	$(CC)as.exe $(CFLAGS) $< -o $@

$(PROJECT_NAME).elf: $(OBJ) $(ASO)
	$(CC)ld.exe -T linker.ld $(LIBS) $(OBJ) $(ASO) -o $@ -Map=mab_file.map

$(PROJECT_NAME).bin: $(PROJECT_NAME).elf
	$(CC)objcopy.exe -O binary $< $@

clean_all:
	rm  *.o *.elf *.bin *.map 
	@echo "everything clean..."

clean:
	rm  *.bin *.elf
	@echo "clean .elf and .bin files"