/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



typedef volatile unsigned int vuint32_t;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

//  GPIOA registers addresses
#define GPIOA_BASE  0x40010800
#define GPIOA_CRH   *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_CRL   *(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_ODR   *(volatile uint32_t *)(GPIOA_BASE + 0x0C)

//  Clock for GPIOA registers addresses
#define RCC_BASE    0x40021000
#define RCC_APB2ENR  *(volatile uint32_t *)(RCC_BASE + 0x18)
#define RCC_CFGR     *(volatile uint32_t *)(RCC_BASE + 0x04)
#define RCC_CR       *(volatile uint32_t *)(RCC_BASE + 0x00)

// EXTI Interrupt Registers Addresses
#define EXTI_BASE      0x40010400
#define EXTI_PR        *(volatile uint32_t *)(EXTI_BASE + 0x14)
#define EXTI_IMR        *(volatile uint32_t *)(EXTI_BASE + 0x00)
#define EXTI_RTSR       *(volatile uint32_t *)(EXTI_BASE + 0x08)

// AFTIO registers addresses
#define AFIO_BASE      0x40010000
#define AFIO_EXTICRl   *(volatile uint32_t *)(AFIO_BASE + 0x08)

//NVIC register address
#define NVIC_ISER0   *(volatile uint32_t *)(0xE000E100)

void GPIOA0_Input_Init(){
	// Init GPIOA0 as Input
	 GPIOA_CRL |= 1<<2;

}

void GPIOA13_Output_Init(){
    // Init GPIOA13 as Output
    GPIOA_CRH &= 0xFF0FFFFF;
    GPIOA_CRH |= 0x00200000;
}

void Clock_Init(){
	// enable clock for GPIOA
	RCC_APB2ENR |= 1<<2;

	// enable clock for AFIO
	AFIO_EXTICRl |= 1<<0;
}
int main(void)
{
	Clock_Init();
	GPIOA13_Output_Init();
	GPIOA0_Input_Init();

	//select portA for EXTI0
	AFIO_EXTICRl = 0x0;

	// enable rising trigger
	EXTI_RTSR |= 1<<0;

	//enable mask EXTI0
	 EXTI_IMR |= 1<<0;

	 //enable NVIC IRQ 6
	 NVIC_ISER0 |= 1<<6;

	 while(1);



}

// EXTI Line0 interrupt
void EXTI0_IRQHandler(){

	// toggle led
	GPIOA_ODR ^= 1 << 13;

	// clear EXTI0 Pending Request
	EXTI_PR |= 1<<0;



}

