/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6.h"
#include "Stm32F103C6_GPIO_Driver.h"
#include "Lcd.h"
#include "KeyPad.h"
#include "Seven_Segment.h"


void clock_init() {
	//Enable clock GPIOA
	RCC_GPIOA_CLK_EN();
	//Enable clock GPIOB
	RCC_GPIOB_CLK_EN();
}

void delay(uint32_t time){
	uint32_t i, j;
	for (i = 0; i < time; i++)
		for (j = 0; j < 255; j++);
}


int main(void)
{
	uint8_t key , status = 0 , operator = 0;

	float num1 = 0, num2 = 0, result = 0;


	clock_init() ;
	LCD_Init();
	Write_String_onLCD("Welcome to Belal Calculator");
	_delay_ms(20);
	Clear_LCD_Screen();

	Write_String_onLCD("Loading.....");
	Init_7Segment();
	for (uint8_t i = 3; i >= 0 ; i--)
	{
		DisplayNumber_on_7segment(i);
	    delay(250);
	    if( i == 0)
	    	break;
	}
	delay(1);
	Clear_LCD_Screen();



	Keypad_Init();
	Write_String_onLCD("Keypad is ready");
	delay(10);
	Clear_LCD_Screen();

	while(1)
	{
		key = GetData_FromKeyPad();

		if(key == 'N') continue; // do nothing

		else if(key == '?')   // clear lcd
		{
			Clear_LCD_Screen();
			num1 = num2 = result = 0;
			operator = 0;
			status = 0;
		}

		else if(key >= '0' && key <= '9')
		{
			Write_Character_onLCD(key);
			if(status == 0) num1 = num1*10 + (key - '0');
			else num2 = num2*10 + (key - '0');
		}

		else if(key == '+' || key == '-' || key == '*' || key == '/')
		{
			Write_Character_onLCD(key);
			operator = key;
			status = 1;
		}

		else if(key == '=')
		{
			Control_LCD_Lines_And_Cursor(2,0);
			Write_String_onLCD("Result = ");
			switch(operator)
			{
				case '+': result = num1 + num2; break;
				case '-': result = num1 - num2; break;
				case '*': result = num1 * num2; break;
				case '/':
				if(num2 != 0) result = num1 / num2;
				else {
					 Clear_LCD_Screen();
					 _delay_ms(20);
					 Write_String_onLCD("ERROR :");
					 Control_LCD_Lines_And_Cursor(2,0);
					 Write_String_onLCD("Divide By 0");
					  continue;
					   }
				break;
			}
			 Display_RealNumber_onnLCD(result);


		}
	}
}


