/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6.h"
#include "Stm32F103C6_GPIO_Driver.h"
#include "Stm32F103C6_EXTI_Driver.h"
#include "Lcd.h"
#include "KeyPad.h"
#include "Seven_Segment.h"

volatile uint8_t IRQ_Flag = 0;

void delay(uint32_t time){
    uint32_t i, j;
    for (i = 0; i < time; i++)
        for (j = 0; j < 255; j++);
}

void IRQ9_Callback()
{
    IRQ_Flag = 1;
}

int main(void)
{
    // enable clocks for GPIOA GPIOB AFIO
	AFIO_GPIOE_CLK_EN();
    RCC_GPIOA_CLK_EN();
    RCC_GPIOB_CLK_EN();

    LCD_Init();

    EXTI_Configure_Pin_t EXTIx;
    EXTIx.EXTI_PIN = EXTI9PB9;
    EXTIx.EDGE_CASE = RISING_EDGE;
    EXTIx.IRQ_E_D = ENABLE_IRQ_EXTI;
    EXTIx.P_IRQ_FUNC_CALLBACK = &IRQ9_Callback;
    MCAL_EXTI_GPIO_Init(&EXTIx);

    while(1)
    {
        if(IRQ_Flag)
        {
            Clear_LCD_Screen();
            Write_String_onLCD("Interrupt triggered on PB9 !");
            IRQ_Flag = 0;
        }
    }
}

