/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "stm32f103x6.h"
#include "Stm32F103C6_GPIO_Driver.h"



//INITs
void Clock_Init()
{
	RCC_GPIOA_CLK_EN();		//enable clock for GPIOA

	RCC_GPIOB_CLK_EN();		//enable clock for GPIOB
}

void GPIO_Init()
{
	GPIO_Configure_Pin_t pinConfig;

	//PA1 Input Highz
	pinConfig.GPOI_Pin_Number = GPIO_PIN1;
	pinConfig.GPIO_Mode = GPIO_Floating_Input;
	MCAL_GPIO_Init(GPIOA, &pinConfig);

	//PB1 Output PP
	pinConfig.GPOI_Pin_Number = GPIO_PIN1;
	pinConfig.GPIO_Mode = output_push_pull ;
	pinConfig.GPIO_Output_Frequency = Frequency_10MHz;
	MCAL_GPIO_Init(GPIOB, &pinConfig);

	//PA13 Input Highz
	pinConfig.GPOI_Pin_Number = GPIO_PIN13;
	pinConfig.GPIO_Mode = GPIO_Floating_Input;
	MCAL_GPIO_Init(GPIOA, &pinConfig);

	//PB1 Output PP
	pinConfig.GPOI_Pin_Number = GPIO_PIN13;
	pinConfig.GPIO_Mode = output_push_pull ;
	pinConfig.GPIO_Output_Frequency =  Frequency_10MHz;
	MCAL_GPIO_Init(GPIOB, &pinConfig);
}

void _delay_ms_(int x){

	unsigned int i,j;
	for (i=0; i<x;i++)
	{
		for(j=0;j<255;j++);
	}
}


int main(void)
{
	Clock_Init();
	GPIO_Init();

    while(1)
    {
    	if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN1) == 0)
    	{
    		MCAL_GPIO_TogglePin(GPIOB,GPIO_PIN1);
    		while((MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN1)) == 0) ;
    	}
    	if((MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN13)) == 1)
    	{
    		MCAL_GPIO_TogglePin(GPIOB,GPIO_PIN13);

    	}
    	_delay_ms_(1);
    }
    return 0;
}
